name: Python Security Check

on:
  push:
    branches:
      - develop
      - master

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install bandit safety

    - name: Run Bandit (Security Linter)
      run: bandit -r . -x B201

    - name: Check for known vulnerabilities in dependencies
      run: safety check
